name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  Build:
    runs-on: ubuntu-latest
    environment: trunk

    steps:

    - uses: actions/checkout@v4
    - name: Get tag
      id: tag
      run: |
        echo tag=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      shell: bash
      run: bash .devops/scripts/run-install-poetry.sh

    - name: Update PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build distributions
      run: |
        poetry build -vvv

    - name: Upload distribution artifacts
      uses: actions/upload-artifact@v4
      with:
        name: project-dist
        path: dist

  Publish:
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: trunk
      url: https://pypi.org/p/azure-poetry-plugin
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: |
          echo tag=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT

      - name: Download distribution artifact
        uses: actions/download-artifact@master
        with:
          name: project-dist
          path: dist

      - name: Install Poetry
        shell: bash
        run: bash .devops/scripts/run-install-poetry.sh

      - name: Update PATH
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check distributions
        run: |
          ls -la dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false